name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get update && sudo apt-get install shellcheck php python3-dev python3-pip python3-wheel python3-setuptools openjdk-8-jdk openjdk-8-jre -y
    - run: ./dev.sh install
    - run: PATH="$PATH:$HOME/.local/bin" ./dev.sh test
